# Set up

In [101]:
# basics
import os
import json
import yaml
import shutil
import zipfile
import random
import numpy as np
import pandas as pd
import json
import re
import requests

# network
import osmnx as ox
import networkx as nx

# spatial
import geopandas as gpd
from shapely.geometry import Point, Polygon, LineString

# vis
import matplotlib.pyplot as plt
import matplotlib.path as mpltPath
import matplotlib.colors as mcolors
import matplotlib.cm as cm
import matplotlib.colors as mcolors
import seaborn as sns 

# reinstall pyprj if you encounter CRS projection issues
# conda install -c conda-forge pyproj --force-reinstall

# Your Study Area or Roads
Select one of the two following processing methods

## if you have YOUR_ROADS

In [113]:
your_input = gpd.read_file("YOUR_ROADS.geojson")
your_input = your_input.to_crs(epsg=4326)
your_input = your_input[["name", "geometry"]]
your_input["midpoint"] = your_input.geometry.apply(lambda line: line.interpolate(line.length / 2))
your_input.geometry = your_input["midpoint"]
your_input = your_input.drop("geometry", axis=1)
your_input = your_input.iloc[10:13] # test on first few road segments
print(len(your_input))
your_input.iloc[0:5]
#your_input.explore()

3

                         name                    midpoint
10  Piedmont Avenue Northeast  POINT (-84.38173 33.77298)
11   Peachtree Walk Northeast   POINT (-84.3863 33.78274)
12      11th Street Northeast  POINT (-84.38547 33.78326)

## if you have YOUR_AREA

In [104]:
your_input = gpd.read_file("YOUR_AREA.geojson")
your_input = your_input.to_crs(epsg=4326)
cf = ('["highway"~"primary|secondary|tertiary|residential"]')
your_input = ox.graph_from_polygon(your_input.geometry[0], 
                                network_type='drive', 
                                custom_filter=cf,
                                simplify=True)
    
your_input = ox.graph_to_gdfs(your_input, nodes=False)
your_input = your_input[["osmid", "highway", "name", "oneway", "length", "geometry"]]
your_input["osmid"] = your_input["osmid"].apply(lambda x: tuple(x) if isinstance(x, list) else x)
your_input["highway"] = your_input["highway"].apply(lambda x: tuple(x) if isinstance(x, list) else x)
your_input["name"] = your_input["name"].apply(lambda x: tuple(x) if isinstance(x, list) else x)
your_input["name"] = your_input["name"].astype(str)
your_input = your_input[your_input["highway"].isin(['primary', 'secondary', 'tertiary', 'residential'])]
your_input = your_input.drop_duplicates(subset=["highway", "length", "geometry"])
your_input = your_input[your_input.index.get_level_values("u") != your_input.index.get_level_values("v")]
your_input = your_input[your_input["length"] > 50]
your_input = your_input.reset_index()
your_input = your_input[["name", "geometry"]]
your_input["midpoint"] = your_input.geometry.apply(lambda line: line.interpolate(line.length / 2))
your_input.geometry = your_input["midpoint"]
your_input = your_input.drop("geometry", axis=1)

print(len(your_input))
your_input.iloc[0:5]
# your_input.explore()

511

                         name                    midpoint
0            Peachtree Street  POINT (-84.38777 33.79514)
1  Peachtree Street Northeast  POINT (-84.38776 33.79623)
2     Spring Street Northwest  POINT (-84.38908 33.79522)
3  Peachtree Street Northeast  POINT (-84.38985 33.79761)
4                         nan   POINT (-84.3901 33.79856)

# Functions

In [82]:
#=== Download OSM Road Network ===
cf = ('["highway"~"primary|secondary|tertiary|residential"]')

#=== Determine Single / Dual Carriageway and Add Relevant Attributes (Median, Num. of Lanes) ===
def angular_diff(a, b):
    """Smallest difference between two angles (0–360)."""
    return min(abs(a - b), 360 - abs(a - b))

def has_opposite_bearings(series, threshold=150):
    bearings = series.dropna().to_numpy()
    n = len(bearings)
    for i in range(n):
        for j in range(i+1, n):
            if angular_diff(bearings[i], bearings[j]) > threshold:
                return True
    return False

def collapse_names(name):
    if isinstance(name, (list, tuple)):
        return str(name[0])
    return name
    
def collapse_lanes(val, how="min"):
    if isinstance(val, (list, tuple)):
        return min(int(x) for x in val if pd.notna(x))
    if pd.notna(val):
        return int(val)
    return pd.NA
    
#=== Find the Nearest Edge ===

#=== Cut Edge into 60m-long Segment ===

#=== Find PanoID Points ===
def sample_line(line, interval=5):
    return [line.interpolate(distance) for distance in range(0, int(line.length), interval)]
    
def _make_url(lat: float, lon: float) -> str:
    return (
        "https://maps.googleapis.com/maps/api/js/GeoPhotoService.SingleImageSearch"
        "?pb=!1m5!1sapiv3!5sUS!11m2!1m1!1b0!2m4!1m2!3d{lat}!4d{lon}!2d50!3m10"
        "!2m2!1sen!2sGB!9m1!1e2!11m4!1m3!1e2!2b1!3e2!4m10!1e1!1e2!1e3!1e4!1e8!1e6!5m1!1e2!6m1!1e2"
        "&callback=callbackfunc"
    ).format(lat=lat, lon=lon)

def _fetch(lat: float, lon: float, timeout: float = 10.0) -> str:
    headers = {
        "User-Agent": "Mozilla/5.0",
        "Accept": "*/*",
        "Referer": "https://maps.google.com/",
    }
    r = requests.get(_make_url(lat, lon), headers=headers, timeout=timeout)
    r.raise_for_status()
    return r.text

def _strip_jsonp(text: str, cb="callbackfunc") -> str:
    m = re.search(rf"{re.escape(cb)}\s*\(\s*(.*)\s*\)\s*;?\s*$", text, re.DOTALL)
    if not m:
        raise ValueError("Could not find JSON payload inside JSONP wrapper.")
    return m.group(1)

def streetview_nearest_df(lat: float, lon: float) -> pd.DataFrame:
    """Return a DataFrame with columns: pano_id, lat, lon, heading, date."""
    payload = _strip_jsonp(_fetch(lat, lon))
    data = json.loads(payload)
    if data == [[5, "generic", "Search returned no images."]]:
        return pd.DataFrame(columns=["pano_id", "lat", "lon", "heading", "date"])
    subset = data[1][5][0]
    raw_panos = subset[3][0]
    raw_dates = [] if (len(subset) < 9 or subset[8] is None) else subset[8]
    raw_panos = raw_panos[::-1]
    raw_dates = raw_dates[::-1]
    dates = []
    for d in raw_dates:
        try:
            dates.append(f"{d[1][0]}-{int(d[1][1]):02d}")  # YYYY-MM
        except Exception:
            dates.append(None)
    rows = []
    for i, p in enumerate(raw_panos):
        try:
            pano_id = p[0][1]
            plat = float(p[2][0][2])
            plon = float(p[2][0][3])
            heading = float(p[2][2][0])
        except Exception:
            continue
        rows.append({
            "pano_id": pano_id,
            "pano_lat": plat,
            "pano_lon": plon,
            "pano_heading": heading,
            "pano_date": dates[i] if i < len(dates) else None
        })
    return pd.DataFrame(rows, columns=["pano_id", "pano_lat", "pano_lon", "pano_heading", "pano_date"])

recent_years = ["2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025"]

def update_geometry(row):
    return Point(row["pano_lon"], row["pano_lat"])

In [83]:
def get_nearest_segmented_gsv_panos(
    COI_for_ox: tuple,
    COI: gpd.GeoDataFrame,
    dist: int = 200,
    cut_length: float = 60,
    buffer_size: float = 30,
    sample_interval: int = 5,
    recent_years: list = None,
):
    """
    Given a center point (GeoDataFrame with 1 row), return segmented edge(s) 
    and deduplicated GSV pano points with attributes.

    Parameters
    ----------
    COI : GeoDataFrame
        A single-point GeoDataFrame in EPSG:4326.
    cf : str
        OSMnx custom_filter string (for filtering highways).
    dist : int, default=200
        Distance (in meters) to search for network around the COI.
    cut_length : float, default=60
        Length (in meters) of road segment to cut around the COI.
    buffer_size : float, default=30
        Buffer radius for cutting the road segment.
    sample_interval : int, default=5
        Interval (in meters) for sampling points along the road segment.
    recent_years : list, optional
        List of allowed pano years as strings. If None, defaults to 2016–2025.

    Returns
    -------
    edges_nearest_segmented : GeoDataFrame
        Segmented road edge(s) near the COI (in EPSG:4326).
    edges_nearest_segmented_gsv_pano_dedup : GeoDataFrame
        Deduplicated pano points with attributes (in EPSG:4326).
    """
    
    # === fixed parameters ===
    recent_years = [str(y) for y in range(2016, 2026)]
    cf = '["highway"~"primary|secondary|tertiary|residential"]'

    # === Download OSM Road Network ===
    try:
        G = ox.graph_from_point(
            COI_for_ox, 
            network_type="all",
            dist=dist,
            dist_type="bbox",
            truncate_by_edge=True,
            custom_filter=cf)
    except ValueError as e:
        print(f"Skipping")
        return None, None
    
    G = ox.bearing.add_edge_bearings(G)
    G = ox.projection.project_graph(G, to_crs=None)
    CRS_UTM = G.graph["crs"]

    nodes, edges = ox.graph_to_gdfs(G)
    COI = COI.to_crs(CRS_UTM)
    edges = edges.to_crs(CRS_UTM)
    edges["dist_to_pt"] = edges.geometry.distance(COI.geometry.iloc[0])
    a = len(edges)
    
    # === Find nearest edges ===
    edges_nearest = edges.sort_values("dist_to_pt").iloc[0:2]
    edges_nearest["name"] = edges_nearest["name"].apply(collapse_names)
    b = len(edges_nearest)

    # === Determine Single / Dual Carriageway and Add Relevant Attributes (Median, Num. of Lanes) ===
    edges_nearest["has_opposite"] = has_opposite_bearings(edges_nearest["bearing"])
    
    # Check conditions step by step
    if len(edges_nearest) > 1:
        both_oneway = (edges_nearest["oneway"].astype(str).iloc[0] == "True") & (edges_nearest["oneway"].astype(str).iloc[1] == "True")
        opposite_bearings = edges_nearest["has_opposite"].iloc[0] & edges_nearest["has_opposite"].iloc[1]
        if both_oneway and opposite_bearings:
            # Dual carriageway -> assign median
            edges_nearest["median"] = "yes"
            edges_nearest = edges_nearest.iloc[0:2]
        else: 
            edges_nearest["median"] = "no"
            edges_nearest = edges_nearest.iloc[0]
            edges_nearest = gpd.GeoDataFrame(pd.DataFrame([edges_nearest]), crs=CRS_UTM)
    else:
        # Single carriageway -> no median
        edges_nearest["median"] = "no"
        edges_nearest = edges_nearest.iloc[0]
        edges_nearest = gpd.GeoDataFrame(pd.DataFrame([edges_nearest]), crs=CRS_UTM)
    c = len(edges_nearest)

    # Collapse lanes and the "name"
    if "lanes" in edges_nearest.columns:
        edges_nearest["lanes_collapsed"] = edges_nearest["lanes"].apply(collapse_lanes, how="min").astype("Int64")
    else:
        edges_nearest["lanes_collapsed"] = 1
    
    if len(edges_nearest) > 1:
        edges_nearest["lanes_collapsed"] = edges_nearest["lanes_collapsed"].sum()
        edges_nearest["name"] = str(edges_nearest.iloc[0]["name"])
    edges_nearest = edges_nearest.drop(["access", "reversed", "maxspeed"], axis=1, errors="ignore")

    # === Cut edge into segment ===
    COI_geom = COI["geometry"].iloc[0]
    edges_nearest["point_on_line"] = edges_nearest.apply(
        lambda row: row.geometry.interpolate(row.geometry.project(COI_geom)).buffer(buffer_size), axis=1
    )
    edges_nearest["geom_cut"] = edges_nearest.apply(
        lambda row: row.geometry.intersection(row.point_on_line), axis=1
    )
    edges_nearest_segmented = gpd.GeoDataFrame(edges_nearest, geometry=edges_nearest["geom_cut"]).drop(
        columns=["point_on_line", "geom_cut"]
    )
    edges_nearest_segmented["length_new"] = edges_nearest_segmented.geometry.length
    edges_nearest_segmented = edges_nearest_segmented.reset_index(drop=True)
    edges_nearest_segmented = edges_nearest_segmented[['osmid', 'name', 'highway', 'oneway', 
                                                       'bearing', 'median', 'lanes_collapsed',
                                                       'length_new', 'geometry']]
    edges_nearest_segmented = edges_nearest_segmented.rename(columns={"highway": "road_type"})
    edges_nearest_segmented["edge_id"] = edges_nearest_segmented['osmid'].astype(str) + "_" + edges_nearest_segmented['bearing'].astype(str)
    d = len(edges_nearest_segmented)
    print(f"edges: {a} -> {b} -> {c} -> {d}")

    # === Sample points ===
    edges_gsv = edges_nearest_segmented.copy()
    edges_gsv["osmid"] = edges_gsv["osmid"].astype(str)
    edges_gsv["edge_id"] = edges_gsv["edge_id"].astype(str)
    edges_gsv = edges_gsv[["osmid", "edge_id", "oneway", "median", "bearing", "name", "geometry"]]
    edges_gsv["sampled_points"] = edges_gsv.geometry.apply(lambda x: sample_line(x, interval=sample_interval))
    edges_gsv = edges_gsv.explode("sampled_points")
    edges_gsv = gpd.GeoDataFrame(edges_gsv, geometry="sampled_points", crs=CRS_UTM)
    edges_gsv = edges_gsv.to_crs(4326)
    edges_gsv["lat"] = edges_gsv.geometry.y
    edges_gsv["lon"] = edges_gsv.geometry.x
    
    # === Query GSV ===
    results = []
    for _, row in edges_gsv.iterrows():
        out = streetview_nearest_df(row.lat, row.lon)
        out["osmid"] = row["osmid"]
        out["edge_id"] = row["edge_id"]
        out["bearing"] = row["bearing"]
        out["median"] = row["median"]
        results.append(out)
    pano_df = pd.concat(results, ignore_index=True)
    if pano_df.empty:
        return None, None   # or pd.DataFrame(), pd.DataFrame()
    #print(pano_df)
    
    pano_df = pano_df[~pano_df["pano_date"].isna()]
    a = len(pano_df)
    if pano_df.empty:
        return None, None   # or pd.DataFrame(), pd.DataFrame()
        
    # Filter by recent years
    pano_df = pano_df[pano_df["pano_date"].apply(lambda x: x.split("-")[0]).isin(recent_years)]
    b = len(pano_df) # 39
    if pano_df.empty:
        return None, None   # or pd.DataFrame(), pd.DataFrame()

    # Mode year filtering
    pano_df["count"] = pano_df.groupby(["osmid", "edge_id", "pano_date"])["pano_date"].transform("count")
    pano_df["max_count"] = pano_df.groupby("edge_id")["count"].transform("max")
    pano_df = pano_df[pano_df["count"] == pano_df["max_count"]]

    # the latest date among the most common dates    
    pano_df["pano_date_dt"] = pd.to_datetime(pano_df["pano_date"], format="%Y-%m", errors="coerce")
    pano_df["pano_date_dt_latest"] = pano_df.groupby("edge_id")["pano_date_dt"].transform("max")
    pano_df = pano_df[pano_df["pano_date_dt"] == pano_df["pano_date_dt_latest"]]
    
    if pano_df.empty:
        return None, None   # or pd.DataFrame(), pd.DataFrame()
    c = len(pano_df) #12
    if pano_df.empty:
        return None, None   # or pd.DataFrame(), pd.DataFrame()

    # Deduplicate
    pano_df = pano_df.drop_duplicates(["edge_id", "pano_id"])
    d = len(pano_df) #6
    pano_df["point_id"] = pano_df.groupby(["edge_id"]).cumcount()
    #pano_df["count"] = pano_df.groupby("pano_date")["pano_date"].transform("count") # update the count info after de-dup
    pano_df["geometry"] = pano_df.apply(update_geometry, axis=1)

    pano_df = pano_df[['osmid', 'edge_id', 'median', 'bearing', 'pano_id', 'pano_lat', 'pano_lon', 'pano_heading', 'pano_date', 'point_id', 'geometry']]

    edges_nearest_segmented_gsv_pano_dedup = gpd.GeoDataFrame(pano_df, geometry="geometry", crs="EPSG:4326")

    e = len(pano_df) #6
    print(f"points: {a} -> {b} -> {c} -> {d} -> {e}")
    #print()
    
    edges_nearest_segmented = edges_nearest_segmented.to_crs(4326)

    return edges_nearest_segmented, edges_nearest_segmented_gsv_pano_dedup

# Run

In [84]:
results_edges = []
results_points = []

for i, row in your_input.iterrows(): 
    #print(f"{i}: {row["name"]}") if you have a name column in YOUR_ROAD dataset
    COI_geom = row["midpoint"]
    COI = gpd.GeoDataFrame(geometry=[COI_geom], crs="EPSG:4326")

    lon = COI_geom.x
    lat = COI_geom.y
    COI_for_ox = tuple([lat, lon]) 

    output_edge, output_point = get_nearest_segmented_gsv_panos(COI_for_ox, COI)
    results_edges.append(output_edge)
    results_points.append(output_point)
    print()
#results

edges: 36 -> 2 -> 1 -> 1
points: 272 -> 164 -> 12 -> 7 -> 7

edges: 44 -> 2 -> 1 -> 1
points: 277 -> 159 -> 12 -> 7 -> 7

edges: 34 -> 2 -> 1 -> 1
points: 202 -> 130 -> 12 -> 6 -> 6

edges: 39 -> 2 -> 1 -> 1

KeyboardInterrupt:

In [85]:
results_edges = pd.concat(results_edges)
print(len(results_edges))
results_edges
#results_edges.explore()

3

,osmid,name,road_type,oneway,bearing,median,lanes_collapsed,length_new,geometry,edge_id
0,"[1321837584, 484857194, 9269453, 96433134]",Peachtree Street,primary,False,176.267759,no,5,59.993729,"LINESTRING (-84.38776 33.79541, -84.38776 33.7...","[1321837584, 484857194, 9269453, 96433134]_176..."
0,"[1321793811, 1322102955]",Peachtree Street Northeast,primary,False,351.831405,no,5,60.024067,"LINESTRING (-84.38775 33.79596, -84.38775 33.7...","[1321793811, 1322102955]_351.8314047002249"
0,"[30978553, 331322111]",Spring Street Northwest,primary,True,181.633932,no,3,59.991666,"LINESTRING (-84.38907 33.79549, -84.38907 33.7...","[30978553, 331322111]_181.63393232976287"

In [86]:
results_points = pd.concat(results_points)
print(len(results_points))
results_points.iloc[0:5]
results_points.explore()

20

# Assign the Sides of the Road

## edges

In [87]:
results_edges_single = results_edges[results_edges["median"] == "no"]
print(len(results_edges_single))
print()
results_edges_single_side1 = results_edges_single.copy()
results_edges_single_side2 = results_edges_single.copy()
print(len(results_edges_single_side1))
results_edges_single_side1["side"] = "side1"
print(results_edges_single_side1.iloc[0:2])
print()
print(len(results_edges_single_side2))
results_edges_single_side2["side"] = "side2"
results_edges_single_side2["bearing"] = (results_edges_single_side2["bearing"] + 180) % 360
print(results_edges_single_side2.iloc[0:2])

3

3
                                        osmid                        name  \
0  [1321837584, 484857194, 9269453, 96433134]            Peachtree Street
0                    [1321793811, 1322102955]  Peachtree Street Northeast

  road_type  oneway     bearing median  lanes_collapsed  length_new  \
0   primary   False  176.267759     no                5   59.993729
0   primary   False  351.831405     no                5   60.024067

                                            geometry  \
0  LINESTRING (-84.38776 33.79541, -84.38776 33.7...
0  LINESTRING (-84.38775 33.79596, -84.38775 33.7...

                                             edge_id   side
0  [1321837584, 484857194, 9269453, 96433134]_176...  side1
0         [1321793811, 1322102955]_351.8314047002249  side1

3
                                        osmid                        name  \
0  [1321837584, 484857194, 9269453, 96433134]            Peachtree Street
0                    [1321793811, 1322102955]  Peachtree Street Northeast

  road_type  oneway     bearing median  lanes_collapsed  length_new  \
0   primary   False  356.267759     no                5   59.993729
0   primary   False  171.831405     no                5   60.024067

                                            geometry  \
0  LINESTRING (-84.38776 33.79541, -84.38776 33.7...
0  LINESTRING (-84.38775 33.79596, -84.38775 33.7...

                                             edge_id   side
0  [1321837584, 484857194, 9269453, 96433134]_176...  side2
0         [1321793811, 1322102955]_351.8314047002249  side2

In [88]:
results_edges_dual = results_edges[results_edges["median"] == "yes"]
print(len(results_edges_dual))

def compare_bearing(g):
    min_bearing = g["bearing"].min()
    return g["bearing"] == min_bearing

results_edges_dual["bearing_smaller"] = results_edges_dual.groupby("edge_id")["bearing"].transform(lambda g: g == g.min()) 
results_edges_dual["side"] = results_edges_dual["bearing_smaller"].map(
    {True: "side1", False: "side2"}
)
results_edges_dual.drop("bearing_smaller", axis=1, inplace=True)
print(len(results_edges_dual))
results_edges_dual.iloc[0:6]

0
0

/tmp/ipykernel_1977477/3252752380.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_edges_dual.drop("bearing_smaller", axis=1, inplace=True)

Empty GeoDataFrame
Columns: [osmid, name, road_type, oneway, bearing, median, lanes_collapsed, length_new, geometry, edge_id, side]
Index: []

In [90]:
results_edges_side_assigned = pd.concat([results_edges_single_side1, results_edges_single_side2, results_edges_dual], axis=0)
results_edges_side_assigned = results_edges_side_assigned.sort_values(["osmid", "edge_id", "side"])
results_edges_side_assigned = results_edges_side_assigned[["osmid", "edge_id", "side", "name", "oneway", "median", "bearing", "lanes_collapsed", "length_new", "geometry"]]
print(len(results_edges_side_assigned))
results_edges_side_assigned.iloc[0:10]
#edge_whole_side_assigned.iloc[-10:]
#edge_whole_side_assigned[edge_whole_side_assigned["median"]=="yes"]

TypeError: unhashable type: 'list'

## points

In [91]:
results_points_single = results_points[results_points["median"] == "no"]
print(len(results_points_single))
print()
results_points_single_side1 = results_points_single.copy()
results_points_single_side2 = results_points_single.copy()
print(len(results_points_single_side1))
results_points_single_side1["side"] = "side1"
print(results_points_single_side1.iloc[0:2])
print()
print(len(results_points_single_side2))
results_points_single_side2["side"] = "side2"
results_points_single_side2["bearing"] = (results_points_single_side2["bearing"] + 180) % 360
print(results_points_single_side2.iloc[0:2])

20

20
                                          osmid  \
22   [1321837584, 484857194, 9269453, 96433134]
108  [1321837584, 484857194, 9269453, 96433134]

                                               edge_id median     bearing  \
22   [1321837584, 484857194, 9269453, 96433134]_176...     no  176.267759
108  [1321837584, 484857194, 9269453, 96433134]_176...     no  176.267759

                    pano_id   pano_lat   pano_lon  pano_heading pano_date  \
22   GPedoOIkQ-jBcDnILbOfMQ  33.795449 -84.387682      9.109577   2024-11
108  ztSewjxWnP0xclvajF2dig  33.795361 -84.387701      9.599669   2024-11

     point_id                    geometry   side
22          0  POINT (-84.38768 33.79545)  side1
108         1   POINT (-84.3877 33.79536)  side1

20
                                          osmid  \
22   [1321837584, 484857194, 9269453, 96433134]
108  [1321837584, 484857194, 9269453, 96433134]

                                               edge_id median     bearing  \
22   [1321837584, 484857194, 9269453, 96433134]_176...     no  356.267759
108  [1321837584, 484857194, 9269453, 96433134]_176...     no  356.267759

                    pano_id   pano_lat   pano_lon  pano_heading pano_date  \
22   GPedoOIkQ-jBcDnILbOfMQ  33.795449 -84.387682      9.109577   2024-11
108  ztSewjxWnP0xclvajF2dig  33.795361 -84.387701      9.599669   2024-11

     point_id                    geometry   side
22          0  POINT (-84.38768 33.79545)  side2
108         1   POINT (-84.3877 33.79536)  side2

In [92]:
results_points_dual = results_points[results_points["median"] == "yes"]
print(len(results_points_dual))

def compare_bearing(g):
    min_bearing = g["bearing"].min()
    return g["bearing"] == min_bearing

results_points_dual["bearing_smaller"] = results_points_dual.groupby("osmid")["bearing"].transform(lambda g: g == g.min()) 
results_points_dual["side"] = results_points_dual["bearing_smaller"].map(
    {True: "side1", False: "side2"}
)
results_points_dual.drop("bearing_smaller", axis=1, inplace=True)
print(len(results_points_dual))
results_points_dual.iloc[0:6]

0
0

/tmp/ipykernel_1977477/3336541104.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_points_dual.drop("bearing_smaller", axis=1, inplace=True)

Empty GeoDataFrame
Columns: [osmid, edge_id, median, bearing, pano_id, pano_lat, pano_lon, pano_heading, pano_date, point_id, geometry, side]
Index: []

In [93]:
results_points_side_assigned = pd.concat([results_points_single_side1, results_points_single_side2, results_points_dual], axis=0)
results_points_side_assigned = results_points_side_assigned.sort_values(["osmid", "edge_id", "side", "point_id"])
results_points_side_assigned = results_points_side_assigned[["osmid", "edge_id", "side", "point_id", "median", "bearing", 
                                                       "pano_id", "pano_lat", "pano_lon", "pano_heading", "pano_date",
                                                       "geometry"]]
print(len(results_points_side_assigned))
results_points_side_assigned.iloc[0:10]
#results_points_side_assigned.iloc[-10:]
#results_points_side_assigned[results_points_side_assigned["median"]=="yes"]

40

,osmid,edge_id,side,point_id,median,bearing,pano_id,pano_lat,pano_lon,pano_heading,pano_date,geometry
22,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side1,0,no,351.831405,g5yPPhu1zhG9mf2KhjDkyQ,33.795933,-84.387672,0.761336,2024-07,POINT (-84.38767 33.79593)
102,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side1,1,no,351.831405,7qik8QzXzi7-GI7JE1JX9g,33.796037,-84.387733,356.222809,2024-07,POINT (-84.38773 33.79604)
182,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side1,2,no,351.831405,ql_oUKZ5Msll2rAcIBuDLw,33.796082,-84.387736,355.473938,2024-07,POINT (-84.38774 33.79608)
400,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side1,3,no,351.831405,lF2SuUtN_M9edi_3_jej_w,33.796173,-84.387746,354.155426,2024-07,POINT (-84.38775 33.79617)
560,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side1,4,no,351.831405,iUITzAWIb7InDRiivxY9Yw,33.796264,-84.387759,352.459686,2024-07,POINT (-84.38776 33.79626)
716,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side1,5,no,351.831405,jiRONXKtSJE69tupc-3srg,33.796398,-84.387786,347.221893,2024-07,POINT (-84.38779 33.7964)
876,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side1,6,no,351.831405,QnsSnIzykKLg3W5joiDZJQ,33.796486,-84.387814,342.802155,2024-07,POINT (-84.38781 33.79649)
22,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side2,0,no,171.831405,g5yPPhu1zhG9mf2KhjDkyQ,33.795933,-84.387672,0.761336,2024-07,POINT (-84.38767 33.79593)
102,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side2,1,no,171.831405,7qik8QzXzi7-GI7JE1JX9g,33.796037,-84.387733,356.222809,2024-07,POINT (-84.38773 33.79604)
182,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side2,2,no,171.831405,ql_oUKZ5Msll2rAcIBuDLw,33.796082,-84.387736,355.473938,2024-07,POINT (-84.38774 33.79608)

In [94]:
def midpoint_flags(group):
    n = len(group)
    # decide which position is midpoint
    if n == 1:
        mid_pos = 0
    elif n % 2 == 1:   # odd
        mid_pos = n // 2
    else:              # even → the one right before middle
        mid_pos = n // 2 - 1

    flags = [False] * n
    flags[mid_pos] = True
    return pd.Series(flags, index=group.index)

# Apply group-wise and attach as new column
results_points_side_assigned["is_midpoint"] = (
    results_points_side_assigned.groupby(["osmid", "edge_id", "side"], group_keys=False)
    .apply(midpoint_flags)
)

print(len(results_points_side_assigned))
results_points_side_assigned.iloc[0:10]

40

/tmp/ipykernel_1977477/2839631827.py:18: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(midpoint_flags)

,osmid,edge_id,side,point_id,median,bearing,pano_id,pano_lat,pano_lon,pano_heading,pano_date,geometry,is_midpoint
22,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side1,0,no,351.831405,g5yPPhu1zhG9mf2KhjDkyQ,33.795933,-84.387672,0.761336,2024-07,POINT (-84.38767 33.79593),False
102,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side1,1,no,351.831405,7qik8QzXzi7-GI7JE1JX9g,33.796037,-84.387733,356.222809,2024-07,POINT (-84.38773 33.79604),False
182,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side1,2,no,351.831405,ql_oUKZ5Msll2rAcIBuDLw,33.796082,-84.387736,355.473938,2024-07,POINT (-84.38774 33.79608),False
400,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side1,3,no,351.831405,lF2SuUtN_M9edi_3_jej_w,33.796173,-84.387746,354.155426,2024-07,POINT (-84.38775 33.79617),True
560,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side1,4,no,351.831405,iUITzAWIb7InDRiivxY9Yw,33.796264,-84.387759,352.459686,2024-07,POINT (-84.38776 33.79626),False
716,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side1,5,no,351.831405,jiRONXKtSJE69tupc-3srg,33.796398,-84.387786,347.221893,2024-07,POINT (-84.38779 33.7964),False
876,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side1,6,no,351.831405,QnsSnIzykKLg3W5joiDZJQ,33.796486,-84.387814,342.802155,2024-07,POINT (-84.38781 33.79649),False
22,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side2,0,no,171.831405,g5yPPhu1zhG9mf2KhjDkyQ,33.795933,-84.387672,0.761336,2024-07,POINT (-84.38767 33.79593),False
102,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side2,1,no,171.831405,7qik8QzXzi7-GI7JE1JX9g,33.796037,-84.387733,356.222809,2024-07,POINT (-84.38773 33.79604),False
182,"[1321793811, 1322102955]","[1321793811, 1322102955]_351.8314047002249",side2,2,no,171.831405,ql_oUKZ5Msll2rAcIBuDLw,33.796082,-84.387736,355.473938,2024-07,POINT (-84.38774 33.79608),False